<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <Authors>James Montemagno &amp; Mooch</Authors>
    <RepositoryUrl>https://github.com/jamesmontemagno/bananify</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
